### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ahknight** [tinted-theming/base16-builder-ruby#1]
Could you document the required Ruby modules needed for this? I had to play a game of run, install, run, install, run, install...

**Comment by ahknight** [comment]
Or at least how to use the Gemfile.  Ruby newbs out there and all.

**Comment by obahareth** [comment]
Sure @ahknight, I'm sorry you had issues, I plan on bundling all this into a gem to make this all easier in the future (when I get some more time). I'm not satisfied with the performance of cloning yet, I'll probably make it into a gem once I improve it, but I'll see what I can do about documenting current requirements.

**Comment by obahareth** [comment]
@ahknight I [updated the README file](https://github.com/obahareth/base16-builder-ruby/commit/47d075d6ebc4e18f146d403b0f932a1a48bf1896), does that seem more helpful to you?
