### ISSUE TITLE
Output at proj/out, not proj/templates/out

### ISSUE THREAD

**Issue by memeplex** [tinted-theming/base16-builder-ruby#3]
The spec is a bit ambiguous regarding this, since it's not clear what the template root is. But all Chris repos (and others too) have the structure:

```
proj
   templates/...
   out/...
```

while your builder produces:

```
proj
   templates/out
```

**Comment by obahareth** [comment]
Thanks for letting me know, I'll look into fixing that after I deal with #2.

**Comment by memeplex** [comment]
You can just do something like:

```
-      rendered_dir = "#{@template_dir}/#{template_file_config["output"]}"
+      rendered_dir = "#{@template_dir}/../#{template_file_config["output"]}"
```
